ARG TAG=1.23.1-alpine

FROM golang:$TAG

WORKDIR /app

COPY Taskfile.yml .

# Install packages
RUN set -eux; \
    # Packages to install
    apk add --no-cache \
        g++ \
        go-task-task \
        git \
        git-lfs \
        jq \
        make \
        nodejs \
        npm \
        python3 \
        rsync \
    && \
    # Clean out directories that don't need to be part of the image
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && \
    npm install -g \
        pnpm \
        npm@^10.0.0 \
    && \
    task tools

ENTRYPOINT ["/bin/sh"]
