# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  VERSION:
    sh: cat code/ts/library/package.json | jq -r .version

tasks:
  tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      # Replace `linux-x64` with `macos-x64` or `macos-arm64` for macOS.
      - test -f code/go/site/tailwindcli || wget -O code/go/site/tailwindcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.21/tailwindcss-extra-linux-x64
      - chmod +x code/go/site/tailwindcli
      - go install github.com/valyala/quicktemplate/qtc@latest

  qtc:
    sources:
      - "**/*.qtpl"
    generates:
      - "**/*.qtpl.go"
    cmds:
      - qtc

  tsbuild:
    deps:
      - qtc
    sources:
      - "**/*.qtpl"
      - "**/package.json"
      - "**/*.ts"
    generates:
      - "bundles/**/*"
    cmds:
      - go run code/go/cmd/tsbuild/main.go
      - cp -r bundles/datastar.js* code/go/site/static/js/
      - mkdir -p code/go/site/static/librarySource
      - rm -rf code/go/site/static/librarySource/*
      - cp -r code/ts/library/src/* code/go/site/static/librarySource/

  libpub:
    requires:
      vars: [VERSION]
    deps:
      - tsbuild
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin --tags
      # - npm publish --access public
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/starfederation/datastar@v{{.VERSION}}
      # - task: deploy

  css:
    dir: code/go/site
    sources:
      - "**/*.templ"
      - "**/*.md"
      - "**/*.go"
    generates:
      - "static/css/site.css"

    cmds:
      - ./tailwindcli build -i src/css/site.css -o static/css/site.css

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    generates:
      - "**/*_templ.go"
    sources:
      - "**/*.templ"
    cmds:
      - templ generate .

  kill:
    method: none
    cmds:
      - fuser -k 8080/tcp > /dev/null 2>&1 || true

  support:
    sources:
      - code/go/**/*.templ
      - code/go/**/*.go
      - code/go/**/*.md
      - code/go/site/static/**/*
    generates:
      - ./datastar-website
    deps:
      - kill
      - tsbuild
      - templ
      - css

  site:
    method: none
    desc: build and run site
    deps:
      - support
    cmds:
      - go mod tidy
      - go build -o ./datastar-website code/go/cmd/site/main.go
      - ./datastar-website

  test:
    dir: code/go/site/smoketests
    deps:
      - support
    cmds:
      - go test -v

  default:
    cmds:
      - task: site
