# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  NAME: "site"
  BIN_NAME: "{{.NAME}}_bin"
  VERSION:
    sh: cat library/package.json| jq -r .version

tasks:
  version:
    cmds:
      - echo {{.VERSION}}
  libpub:
    dir: ./library
    deps:
      - library
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin --tags
      - npm publish --access public
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/datastar@v{{.VERSION}}
      - task: deploy

  library:
    vars:
      BACKEND_STATIC_DIR: "../backends/go/{{.NAME}}/static/library"
    dir: library
    generates:
      - "dist/**/*"
    sources:
      - "src/**/*.ts"
      - "package.json"
    cmds:
      # - echo "{{.BACKEND_STATIC_DIR}}"
      - pnpm i
      # - pnpm vitest --watch=false
      - pnpm prettier src -w --log-level silent
      - pnpm build
      - rsync -av dist/ {{.BACKEND_STATIC_DIR}}
      - rsync -av package.json {{.BACKEND_STATIC_DIR}}

  css:
    vars:
      BACKEND_STATIC_DIR: "../backends/go/{{.NAME}}/static/css"
    dir: library
    generates:
      - "{{.BACKEND_STATIC_DIR}}"
    sources:
      - "**/*.md"
      - "../backends/go/site/**/*.go"
    cmds:
      - pnpm unocss

  kill:
    cmds:
      - killall -q {{.BIN_NAME}}  || echo "Process was not running."

  hot:
    desc: Server hot reload
    dir: backends/go
    env:
      ENV: dev
    sources:
      - "**/*.go"
      - "**/*.md"
      - "{{.NAME}}/static/**/*"
    deps:
      - kill
      - library
      # - css

    cmds:
      - go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/main.go
      - ./{{.BIN_NAME}}

  deploy:
    deps:
      - library
    cmds:
      - fly deploy --local-only

  default:
    deps:
      - hot
    silent: true
