# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  NAME: "site"
  BIN_NAME: "{{.NAME}}_bin"
  VERSION:
    sh: cat packages/library/package.json| jq -r .version

tasks:
  tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest

  version:
    cmds:
      - echo {{.VERSION}}

  libpub:
    dir: packages/library
    deps:
      - library
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin --tags
      - npm publish --access public
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/datastar@v{{.VERSION}}
      - task: deploy

  library:
    vars:
      BACKEND_STATIC_DIR: "../../backends/go/{{.NAME}}/static/library"
    dir: packages/library
    generates:
      - "dist/**/*"
    sources:
      - "src/**/*.ts"
      - "package.json"
    cmds:
      # - echo "{{.BACKEND_STATIC_DIR}}"
      - pnpm i
      # - pnpm vitest --watch=false
      - pnpm prettier -w .
      - pnpm build
      - rsync -av dist/ {{.BACKEND_STATIC_DIR}}
      - rsync -av package.json {{.BACKEND_STATIC_DIR}}

  inspector:
    library:
    vars:
      BACKEND_STATIC_DIR: "../../backends/go/{{.NAME}}/static/inspector"
    dir: packages/inspector
    generates:
      - "dist/**/*"
    sources:
      - "src/**/*.ts"
      - "package.json"
    cmds:
      # - echo "{{.BACKEND_STATIC_DIR}}"
      - pnpm i
      # - pnpm vitest --watch=false
      - pnpm prettier -w . --log-level silent
      - pnpm build
      - rsync -av dist/ {{.BACKEND_STATIC_DIR}}
      - rsync -av package.json {{.BACKEND_STATIC_DIR}}

  css:
    dir: backends/go/site/css
    generates:
      - "../static/css/site.css"
    sources:
      - "../**/*.md"
      # - "../**/*.go"
      - "../**/*.templ"
    cmds:
      - pnpm i
      - pnpm tailwindcss build -o ../static/css/site.css -w

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    generates:
      - "**/*_templ.go"
    sources:
      - "**/*.templ"
    cmds:
      - templ generate .

  kill:
    cmds:
      - killall -q {{.BIN_NAME}}  || echo "Process was not running."

  tests:
    dir: packages/playwright
    cmds:
      - pnpm i
      - '[ -n "$PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS" ] && echo skip downloading browsers || pnpm playwright install'
      - pnpm playwright

  hot:
    desc: Server hot reload
    dir: backends/go
    env:
      ENV: dev
    sources:
      - "**/*.go"
      - "**/*.md"
      - "{{.NAME}}/static/**/*"
    deps:
      - library
      - kill
      - templ
      # - inspector
      # - css

    cmds:
      - go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/main.go
      - ./{{.BIN_NAME}}

  test:
    dir: packages/playwright
    cmds:
      - curl -o - -I http://localhost:8080
      - pnpm i
      - '[ -n "$PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS" ] && echo skip downloading browsers || pnpm playwright install'
      - pnpm playwright test --ui

  deploy:
    deps:
      - library
    cmds:
      - fly deploy --local-only

  default:
    deps:
      - hot
    silent: true
