package sdk.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum EventType {

    /**
     * An event for merging HTML fragments into the DOM.
     */
    MERGE_FRAGMENTS("datastar-merge-fragments"),

    /**
     * An event for merging signals into the store.
     */
    MERGE_SIGNALS("datastar-merge-signals"),

    /**
     * An event for removing HTML fragments from the DOM.
     */
    REMOVE_FRAGMENTS("datastar-remove-fragments"),

    /**
     * An event for removing signals from the store.
     */
    REMOVE_SIGNALS("datastar-remove-signals"),

    /**
     * An event for executing <script/> elements in the browser.
     */
    EXECUTE_SCRIPT("datastar-execute-script");

//    /**
//     * An event for merging HTML fragments into the DOM.
//     */
//    MERGE_FRAGMENTS("datastar-merge-fragments"),
//
//    /**
//     * An event for merging signals into the store.
//     */
//    MERGE_SIGNALS("datastar-merge-signals"),
//
//    /**
//     * An event for removing HTML fragments from the DOM.
//     */
//    REMOVE_FRAGMENTS("datastar-remove-fragments"),
//
//    /**
//     * An event for removing signals from the store.
//     */
//    REMOVE_SIGNALS("datastar-remove-signals"),
//
//    /**
//     * An event for executing <script/> elements in the browser.
//     */
//    EXECUTE_SCRIPT("datastar-execute-script");

    private final String value;

    EventType(String value) {
        this.value = value;
    }

    /**
     * Returns the string value associated with the enum constant.
     */
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }
}
