package sdk.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum FragmentMergeMode {
    /**
     * Morphs the fragment into the existing element using idiomorph.
     */
    MORPH("morph"),

    /**
     * Replaces the inner HTML of the existing element.
     */
    INNER("inner"),

    /**
     * Replaces the outer HTML of the existing element.
     */
    OUTER("outer"),

    /**
     * Prepends the fragment to the existing element.
     */
    PREPEND("prepend"),

    /**
     * Appends the fragment to the existing element.
     */
    APPEND("append"),

    /**
     * Inserts the fragment before the existing element.
     */
    BEFORE("before"),

    /**
     * Inserts the fragment after the existing element.
     */
    AFTER("after"),

    /**
     * Upserts the attributes of the existing element.
     */
    UPSERT_ATTRIBUTES("upsertAttributes");

    private final String value;

    FragmentMergeMode(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }
}
