//package sdk;
//
//import sdk.enums.FragmentMergeMode;
//
///**
// * This is auto-generated by Datastar. DO NOT EDIT.
// */
//public final class Consts {
//
//    public static final String DATASTAR_KEY = "datastar";
//    public static final String VERSION = "0.20.0-beta-2";
//    public static final int VERSION_CLIENT_BYTE_SIZE = 42952;
//    public static final int VERSION_CLIENT_BYTE_SIZE_GZIP = 14720;
//    public static final int DEFAULT_SETTLE_DURATION = 300;
//    public static final int DEFAULT_SSE_RETRY_DURATION = 1000;
//    public static final boolean DEFAULT_FRAGMENTS_USE_VIEW_TRANSITIONS = false;
//    public static final boolean DEFAULT_MERGE_SIGNALS_ONLY_IF_MISSING = false;
//    public static final boolean DEFAULT_EXECUTE_SCRIPT_AUTO_REMOVE = true;
//    public static final boolean DEFAULT_CUSTOM_EVENT_CANCELABLE = true;
//    public static final boolean DEFAULT_CUSTOM_EVENT_COMPOSED = true;
//    public static final boolean DEFAULT_CUSTOM_EVENT_BUBBLES = true;
//    public static final String DEFAULT_EXECUTE_SCRIPT_ATTRIBUTES = "type module";
//    public static final String DEFAULT_CUSTOM_EVENT_SELECTOR = "document";
//    public static final String DEFAULT_CUSTOM_EVENT_DETAIL_JSON = "{}";
//    public static final FragmentMergeMode DEFAULT_FRAGMENT_MERGE_MODE = FragmentMergeMode.MORPH;
//    public static final String SELECTOR_DATALINE_LITERAL = "selector ";
//    public static final String MERGE_MODE_DATALINE_LITERAL = "mergeMode ";
//    public static final String SETTLE_DURATION_DATALINE_LITERAL = "settleDuration ";
//    public static final String FRAGMENTS_DATALINE_LITERAL = "fragment ";
//    public static final String USE_VIEW_TRANSITION_DATALINE_LITERAL = "useViewTransition ";
//    public static final String SIGNALS_DATALINE_LITERAL = "signals ";
//    public static final String ONLY_IF_MISSING_DATALINE_LITERAL = "onlyIfMissing ";
//    public static final String PATHS_DATALINE_LITERAL = "paths ";
//    public static final String SCRIPT_DATALINE_LITERAL = "script ";
//    public static final String ATTRIBUTES_DATALINE_LITERAL = "attributes ";
//    public static final String AUTO_REMOVE_DATALINE_LITERAL = "autoRemove ";
//
//    // Private constructor to prevent instantiation
//    private Consts() {
//        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
//    }
//}
package sdk;

import sdk.enums.FragmentMergeMode;

public class Consts {
    public static final String DATASTAR_KEY = "datastar";
    public static final FragmentMergeMode DEFAULT_FRAGMENT_MERGE_MODE = FragmentMergeMode.MORPH;
    public static final int DEFAULT_SETTLE_DURATION = 300;
    public static final boolean DEFAULT_FRAGMENTS_USE_VIEW_TRANSITIONS = false;
    public static final int DEFAULT_SSE_RETRY_DURATION = 1000;
    public static final String PATHS_DATALINE_LITERAL = "paths ";

    public static final boolean DEFAULT_MERGE_SIGNALS_ONLY_IF_MISSING = false;

    public static final String SELECTOR_DATALINE_LITERAL = "selector";
    public static final String MERGE_MODE_DATALINE_LITERAL = "mergeMode";
    public static final String SETTLE_DURATION_DATALINE_LITERAL = "settleDuration";
    public static final String USE_VIEW_TRANSITION_DATALINE_LITERAL = "useViewTransition";
    public static final String EVENT_ID_DATALINE_LITERAL = "id";
    public static final String RETRY_DURATION_DATALINE_LITERAL = "retryDuration";
    public static final String FRAGMENTS_DATALINE_LITERAL = "fragments";


    public static final String SIGNALS_DATALINE_LITERAL = "signals";
    public static final String ONLY_IF_MISSING_DATALINE_LITERAL = "onlyIfMissing";
    public static final String SCRIPT_DATALINE_LITERAL = "script";
    public static final String ATTRIBUTES_DATALINE_LITERAL = "attributes";
    public static final String AUTO_REMOVE_DATALINE_LITERAL = "autoRemove";
    public static final String CUSTOM_EVENT_CANCELABLE_DATALINE_LITERAL = "cancel";
    public static final String CUSTOM_EVENT_COMPOSED_DATALINE_LITERAL = "composed";
    public static final String CUSTOM_EVENT_BUBBLES_DATALINE_LITERAL = "bubbles";
    public static final String CUSTOM_EVENT_SELECTOR_DATALINE_LITERAL = "selector";
    public static final String CUSTOM_EVENT_DETAIL_JSON_DATALINE_LITERAL = "detailJson";

}
