package starfederation.datastar.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum EventType {

    // An event for merging HTML fragments into the DOM.
    MergeFragments("datastar-merge-fragments"),

    // An event for merging signals.
    MergeSignals("datastar-merge-signals"),

    // An event for removing HTML fragments from the DOM.
    RemoveFragments("datastar-remove-fragments"),

    // An event for removing signals.
    RemoveSignals("datastar-remove-signals"),

    // An event for executing &lt;script/&gt; elements in the browser.
    ExecuteScript("datastar-execute-script");

    private final String value;

    EventType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}