name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          Thanks for your contribution! This repository is a read-only subset of the Datastar monorepo. Please open your pull request there instead:
          https://github.com/starfederation/datastar
